sudo: required
services:
  - docker

before_install:
  - docker build -t tongnakub/react-test -f ./client/dev.Dockerfile ./client

script:
  - docker run tongnakub/react-test npm run test -- --coverage

after_success:
  - docker build -t tongnakub/multi-client ./client
  - docker build -t tongnakub/multi-server ./server
  - docker build -t tongnakub/multi-worker ./worker
  - docker build -t tongnakub/multi-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push tongnakub/multi-client
  - docker push tongnakub/multi-server
  - docker push tongnakub/multi-worker
  - docker push tongnakub/multi-nginx

# deploy:
#   provider: elasticbeanstalk
#   region: 'ap-southeast-1'
#   app: 'multi-docker'
#   env: 'MultiDocker-env',
#   bucket_name: 'elasticbeanstalk-ap-southeast-1-306476627547'
#   bucket_path: 'multi-docker'
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: '$AWS_SECRET_KEY'
